version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: irctc-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://johndoe:randompassword@postgres:5432/mydb?schema=public"

volumes:
  postgres-data:
